### ISSUE TITLE
java.net.SocketTimeoutException: Connection timed out

### ISSUE THREAD

**Issue by Logistix84** [ways/BigBrotherGPSweb#2]
Thank you very much for the project. Very informative and interesting. But I have a problem. I downloaded it, compile (using IntellijIDEA) and run on my Motorola MB520. Then i set the server url in the android app (url will send post into my own php server with static IP). GPS works OK. But i'm getting java.net.SocketTimeoutException: Connection timed out.  I tested this on a hispeed wi-fi. Sorry for my english. Thank you for your reply.
logcat:
05-20 00:25:42.133    7972-7972/org.gnarf.bigbrother.gps I/System.out﹕ BigBrotherGPS: Received Timeout!
05-20 00:25:42.133    7972-7972/org.gnarf.bigbrother.gps I/System.out﹕ BigBrotherGPS: Doing timeout
05-20 00:25:42.133    7972-7972/org.gnarf.bigbrother.gps I/System.out﹕ BigBrotherGPS: Switching locator
05-20 00:25:43.781    7972-7972/org.gnarf.bigbrother.gps I/System.out﹕ BigBrotherGPS got loc from gps
05-20 00:25:53.859    7972-7977/org.gnarf.bigbrother.gps I/dalvikvm﹕ threadid=4: reacting to signal 3
05-20 00:25:53.938    7972-7977/org.gnarf.bigbrother.gps I/dalvikvm﹕ Wrote stack traces to '/data/anr/traces.txt'
05-20 00:26:04.875    7972-7972/org.gnarf.bigbrother.gps I/System.out﹕ BigBrotherGPS: java.net.SocketTimeoutException: Connection timed out
05-20 00:26:27.203    7972-7972/org.gnarf.bigbrother.gps I/System.out﹕ BigBrotherGPS: Received Timeout!
05-20 00:26:27.203    7972-7972/org.gnarf.bigbrother.gps I/System.out﹕ BigBrotherGPS: Doing timeout
05-20 00:26:27.203    7972-7972/org.gnarf.bigbrother.gps I/System.out﹕ BigBrotherGPS: Switching locator
05-20 00:26:28.836    7972-7972/org.gnarf.bigbrother.gps I/System.out﹕ BigBrotherGPS got loc from gps
05-20 00:26:49.883    7972-7972/org.gnarf.bigbrother.gps I/System.out﹕ BigBrotherGPS: java.net.SocketTimeoutException: Connection timed out

**Comment by Logistix84** [comment]
Solved.
Add this lines in GPS.java:
con = (HttpURLConnection)this.target_url.openConnection();
            **con.setReadTimeout(10000);
            con.setConnectTimeout(10000);**

**Comment by ways** [comment]
Hi. Thanks for the bug report, but it should go to http://bk.gnarf.org/creativity/bigbrothergps/. This repo is just for the web backend.
